id: org.jboss.swagger:swagger-addon
name: Swagger Addon
description: Configure and generate Swagger spec files based on your REST endpoints.
website: https://github.com/rmpestano/swagger-addon
repo: https://github.com/rmpestano/swagger-addon.git
installCmd: addon-install-from-git --url https://github.com/rmpestano/swagger-addon.git
ref: master
tags: swagger, rest, JAXRS
logo: https://swagger.io/swagger/media/assets/images/swagger_logo.svg
author:
  name: Rafael Pestano
  avatar_url: https://pt.gravatar.com/userimage/22997497/1fa9c4a514eaf5b1ebc92f795741203e.png
